<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Muthukumar" failures="1" tests="3" name="com.loginTestOne.MakeMyTrip.TestRunner" time="0.135" errors="0" timestamp="24 Apr 2023 07:24:20 GMT" skipped="2">
  <testcase classname="com.loginTestOne.MakeMyTrip.TestRunner" name="chrome" time="0.000">
    <skipped/>
  </testcase> <!-- chrome -->
  <testcase classname="com.loginTestOne.MakeMyTrip.TestRunner" name="firefox" time="0.000">
    <skipped/>
  </testcase> <!-- firefox -->
  <testcase classname="com.loginTestOne.MakeMyTrip.TestRunner" name="validation" time="0.135">
    <failure message="The following asserts failed:
	expected [MakemyTrip] but found [MakeMyTrip - #1 Travel Website 50% OFF on Hotels, Flights &amp; Holiday]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [MakemyTrip] but found [MakeMyTrip - #1 Travel Website 50% OFF on Hotels, Flights & Holiday]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.loginTestOne.MakeMyTrip.TestRunner.validation(TestRunner.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validation -->
</testsuite> <!-- com.loginTestOne.MakeMyTrip.TestRunner -->
